2025-07-30 01:32:21,260 - factorio_bot - CRITICAL - Bot crashed: DISCORD_TOKEN must be set
Traceback (most recent call last):
  File "D:\Spiele\Factorio bot\BOT\factorio_bot\bot.py", line 127, in run_bot
    bot = FactorioBot()
          ^^^^^^^^^^^^^
  File "D:\Spiele\Factorio bot\BOT\factorio_bot\bot.py", line 39, in __init__
    Config.validate()
  File "D:\Spiele\Factorio bot\BOT\factorio_bot\config.py", line 27, in validate
    raise ValueError("DISCORD_TOKEN must be set")
ValueError: DISCORD_TOKEN must be set
2025-07-30 01:33:07,317 - factorio_bot - CRITICAL - Bot crashed: 'FactorioBot' object has no attribute 'on_interaction'
Traceback (most recent call last):
  File "D:\Spiele\Factorio bot\BOT\factorio_bot\bot.py", line 127, in run_bot
    bot = FactorioBot()
          ^^^^^^^^^^^^^
  File "D:\Spiele\Factorio bot\BOT\factorio_bot\bot.py", line 42, in __init__
    self._register_events()
  File "D:\Spiele\Factorio bot\BOT\factorio_bot\bot.py", line 48, in _register_events
    self.event(self.on_interaction)
               ^^^^^^^^^^^^^^^^^^^
AttributeError: 'FactorioBot' object has no attribute 'on_interaction'
2025-07-30 01:34:49,224 - factorio_bot - INFO - Logged in as factorio server bot#3444
2025-07-30 01:35:50,949 - factorio_bot - INFO - Logged in as factorio server bot#3444
2025-07-30 01:37:00,632 - factorio_bot - INFO - Logged in as factorio server bot#3444
2025-07-30 02:04:40,282 - factorio_bot - INFO - Logged in as factorio server bot#3444
2025-07-30 02:12:23,665 - factorio_bot - INFO - Logged in as factorio server bot#3444
2025-07-30 02:30:45,400 - factorio_bot - INFO - Logged in as factorio server bot#3444
2025-07-30 02:34:39,073 - factorio_bot - INFO - Logged in as factorio server bot#3444
2025-07-30 02:39:17,260 - factorio_bot - INFO - Logged in as factorio server bot#3444
2025-07-30 12:11:14,725 - factorio_bot - INFO - Logged in as factorio server bot#3444
